name: Windows_CI
on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  Onnxruntime-TVM:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8.x'
          architecture: 'x64'

#      - name: Install LLVM and Clang
#        uses: KyleMayes/install-llvm-action@v1
#        with:
#          version: "10.0"

#      - name: Set up Clang
#        uses: egor-tensin/setup-clang@v1
#        with:
#          version: latest
#          platform: x64

      - name: 'Test'
        run: |
          ls -r "C:\Program Files\LLVM"

      - name: 'Setup TVM EP requirements'
        run: |
          python3 -m pip install -r ${{ github.workspace }}/tools/ci_build/github/linux/tvm/requirements.txt
      - name: 'Build and Test'
        run: |
          python3 ${{ github.workspace }}/tools/ci_build/build.py --build_dir build --config Release --skip_submodule_sync --parallel --enable_pybind --disable_contrib_ops --disable_ml_ops --skip_onnx_tests --use_tvm --llvm_config "C:/Program Files/LLVM/bin/llvm-config.exe"
